### ISSUE TITLE
NavBar components are very complex

### ISSUE THREAD

**Issue by sagarpatke** [stackroute/quizztack-web#4]
There are a lot of components coming into play here: NavBar, NavigationComponent, Toolbar and 2 Drawers.

1. NavBar can be safely removed, and NavigationComponent be used instead.
2. Toolbar is the wrong choice of component, as it's used for implementing a custom Toolbar. We need an AppBar here.
3. Replace all links with this.context.router.push() within the drawer.
4. Should navigate back to dashboard when the App name is clicked.
5. AppBar should contain only two icons: Notifications, and Avatar. Avatar should contain links to Edit Profile, Change Password, and Sign out.
6. Notifications should come from JSON Server.

**Comment by dsrini94** [comment]
NavBar can be safely removed, and NavigationComponent be used instead.
Toolbar is the wrong choice of component, as it's used for implementing a custom Toolbar. We need an AppBar here.
Replace all links with this.context.router.push() within the drawer.
Should navigate back to dashboard when the App name is clicked.
AppBar should contain only two icons: Notifications, and Avatar. Avatar should contain links to Edit Profile, Change Password, and Sign out.
Notifications should come from JSON Server.
