### ISSUE TITLE
DashboardMyChallenges component is too complex, and inappropriately named.

### ISSUE THREAD

**Issue by sagarpatke** [stackroute/quizztack-web#5]
Refactor DashboardMyChallenges component:

There needs to be a component which can be displayed directly on the dashboard (`MyChallenges`). This should contain a list of challenges (`Challenge`). On clicking on a challenge, a `Dialog` needs to appear, hence it should be a part of `Challenge` .

**Comment by dsrini94** [comment]
Refactor DashboardMyChallenges component:

There needs to be a component which can be displayed directly on the dashboard (MyChallenges). This should contain a list of challenges (Challenge). On clicking on a challenge, a Dialog needs to appear, hence it should be a part of Challenge .
