### ISSUE TITLE
Create Challenge

### ISSUE THREAD

**Issue by kirtijalan** [stackroute/quizztack-web#6]
1) use intervals (5,10,15,20,30,40,50,80,100) for input type = number
maximum limit : 100

2) negative score

3) Image URL

4) multiple challenge selection

5) include seconds

**Comment by dsrini94** [comment]
use intervals (5,10,15,20,30,40,50,80,100) for input type = number
maximum limit : 100

negative score

Image URL

multiple challenge selection

include seconds
